version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      chrome:
        patterns:
          - "*chrome*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
