name: Release

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.x'

      - name: Build
        run: |
          go build -ldflags "-s -w" -o hlsdl ./cmd
          GOOS=windows go build -ldflags "-s -w" -o hlsdl.exe ./cmd
          echo "::set-output name=date::$(TZ=PRC date +'%Y-%m-%d')"

      - name: Upload Release Asset
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: hlsdl*
