name: Release

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Build
        run: |
          go build -ldflags "-s -w" -o hlsdl-linux-amd64 ./cmd
          GOARCH=arm64 GOOS=darwin go build -ldflags "-s -w" -o hlsdl-darwin-arm64 ./cmd
          GOOS=windows go build -ldflags "-s -w" -o hlsdl-windows-amd64.exe ./cmd
          echo "date=$(TZ=PRC date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Upload Release Asset
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: hlsdl*
